### ISSUE TITLE
Figure out why HTTP response codes not being set correctly

### ISSUE THREAD

**Issue by derek63** [esbtools/esb-resync-gateway#8]
See https://github.com/esbtools/esb-resync-gateway/blob/master/src/main/java/org/esbtools/gateway/resync/ResyncGateway.java#L43 and https://github.com/esbtools/esb-resync-gateway/blob/master/src/main/java/org/esbtools/gateway/resync/ResyncGateway.java#L49

**Comment by alechenninger** [comment]
I think `@ResponseStatus` is being misused there, see: http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-ann-annotated-exceptions

Few options:
1. Define custom exceptions with `@ResponseStatus`
2. Define exception handler methods which return a `ResponseEntity` and accept the exception type thrown (see http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-ann-exceptionhandler)
3. Just return `ResponseEntity` from the gateway resync method call and configure appropriately
