### ISSUE TITLE
Test using spring mvc

### ISSUE THREAD

**Issue by alechenninger** [esbtools/esb-resync-gateway#9]
This will allow you to reproduce problems like in #8 

http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#spring-mvc-test-framework

IMO even though these are a little "higher level" than strictly unit tests, I think they are close enough (and more practically relevant), that using Spring MVC test framework can completely supercede most straight up "unit" style tests without it. That is, no need to test the controller API's directly if we can test it using a mock HTTP request instead (which will catch more real world issues and is still 99% as fast as a more lower level unit test).

**Comment by derek63** [comment]
@alechenninger Perhaps this is no longer needed since I switched to using ResponseEntity as a return type, and can unit test the gateway class directly now?

**Comment by alechenninger** [comment]
That's fine with me. Personally I still think using MVC test framework gives us a little more confidence, but I could be swayed.

**Comment by derek63** [comment]
Lets leave the issue open then, and we can add that in the future.

**Comment by alechenninger** [comment]
Sounds good to me
